name: LobbyCore
version: '${version}'
main: wtf.bytez.LobbyCore
api-version: '1.21'
author: bytezlol
description: Lobby management plugin to make your life easier
folia-supported: true
softdepend: [LuckPerms, PlaceholderAPI]

commands:
  lobbycore:
  discord:
  store:

permissions:
  lobbycore.admin:
    default: op
  lobbycore.chat.colors:
    default: false
  lobbycore.chat.rgb:
    default: false