name: LobbyCore
version: '${version}'
main: net.pikzstudios.LobbyCore
api-version: '1.21'
author: USpigot
description: Lobby management plugin for the Lobby Setup by Pikz.
folia-supported: true
softdepend: [ PlaceholderAPI ]

commands:
  lobbycore:
  discord:
  store:
  setlobby:
  lobby:

permissions:
  lobbycore.admin:
    description: admin access to lobbycore commands.
    default: op