[versions]
paper = "1.21.4-R0.1-SNAPSHOT"
lombok = "1.18.42"
run-paper = "2.3.1"
shadow = "9.4.1"
folialib = "0.5.1"
placeholderapi = "2.12.2"
luckperms = "5.5"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
folialib = { group = "com.tcoded", name = "FoliaLib", version.ref = "folialib" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }